name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v3
    with:
      folders: |
        [
          ".",
          "e2e/smoke"
        ]
      exclude: |
        [
          {"folder": ".", "bzlmodEnabled": false},
          {"bazelversion": "5.4.0", "bzlmodEnabled": true},
          {"bazelversion": "5.4.0", "os": "macos-latest"},
          {"bazelversion": "5.4.0", "os": "windows-latest"},
        ]
  ldc:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1.3.0
        with:
          compiler: ldc-1.32.0
      - name: Bruh
        run: |
          pushd e2e/smoke
          ldc2 -v app/main.d
  dmd:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1.3.0
        with:
          compiler: dmd-2.105.0
      - name: Bruh
        run: |
          pushd e2e/smoke
          dmd -v app/main.d
          bazel build --enable_bzlmod -s //app:app || cat bazel-out/darwin-fastbuild/bin/app/app-2.params
